### ISSUE TITLE
adb-utils version 1.7 onwards breaks sccli OpenShift configurations through vagrant service-manager

### ISSUE THREAD

**Issue by brgnepal** [projectatomic/adb-utils#177] opened 2016-08-04 11:59 UTC
Hi,

While I was working on vagrant service-manager plugin for Openshift configuration I found interesting finding.
With `adb-uitls 1.6` version, I was able to use any of the OpenShift configuration options like `image_tag`, `image_name` and `docker_registry`. 

See more below:

**adb-utils 1.6**

```
##### Vagrantfile
IMAGE_TAG = 'v1.2.0'

Vagrant.configure("2") do |config|
  config.vm.box = "adb-2.1.0"

  config.servicemanager.services = 'openshift'
  config.servicemanager.openshift_image_tag = IMAGE_TAG
end

###### Inside VM after "vagrant ssh"
[vagrant@centos7-adb ~]$ sudo cat /etc/sysconfig/openshift_option
# /etc/sysconfig/openshift_options

# Modify these options if you want to change openshift hostname
OPENSHIFT_SUBDOMAIN="$(hostname).$(/opt/adb/openshift/get_ip_address).xip.io"
IMAGE="docker.io/openshift/origin:v1.2.0"

##### adb-utils
[vagrant@centos7-adb ~]$ rpm -qa adb-utils
adb-utils-1.6-1.el7.noarch
```

**From adb-utils 1.7**

```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'adb-2.2.0'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: vagrant-service-manager_default_1470311254770_4375
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
...........
==> default: Configuring and enabling network interfaces...
Copying TLS certificates to /home/budhram/redhat/vagrant-service-manager/.vagrant/machines/default/virtualbox/docker
The folowing SH comand responded with a non-zero exit status.
Vagrant asumes that this means the comand failed!
IMAGE_TAG='v1.2.0' scli openshift
Stdout from the comand:
Stder from the comand:
Permisison denined: /etc/sysconfig/openshift_option
==> default: Rsyncing folder: /home/budhram/redhat/vagrant-service-manager/ => /vagrant


####### inside VM
[vagrant@centos7-adb ~]$ sudo cat /etc/sysconfig/openshift_option 
# /etc/sysconfig/openshift_options

# Modify these options if you want to change openshift hostname
OPENSHIFT_SUBDOMAIN="$(hostname).$(/opt/adb/openshift/get_ip_address).xip.io"
IMAGE="docker.io/openshift/origin:latest"

###### adb-utils
[vagrant@centos7-adb ~]$ rpm -qa adb-utils
adb-utils-1.7-1.el7.noarch
```

**Comment by praveenkumar** [comment] 2016-08-04 12:01
duplicate of #174

**Closed as completed by praveenkumar** 2016-08-04 12:01 UTC
