### ISSUE TITLE
Documentation for changing from xip.io to nip.io or equivalent.

### ISSUE THREAD

**Issue by LalatenduMohanty** [projectatomic/adb-utils#107] opened 2016-04-15 05:01 UTC
If an user wants to move from from xip.io to nip.io or something equivalent  we need provide documentation for it.

**Comment by LalatenduMohanty** [comment] 2016-04-15 05:14
The information lives in /etc/sysconfig/openshift_options

```
[vagrant@rhel-cdk sysconfig]$ pwd
/etc/sysconfig

[vagrant@rhel-cdk sysconfig]$ cat openshift_option 
# /etc/sysconfig/openshift_options

# Modify these options if you want to change openshift hostname
OPENSHIFT_SUBDOMAIN="$(hostname).$(/opt/adb/openshift/get_ip_address).xip.io"
IMAGE="registry.access.redhat.com/openshift3/ose:v3.1.1.6"
```

**Comment by praveenkumar** [comment] 2016-04-15 06:18
Three different way we can do that.
- Overwrite openshift_options in Vagrantfile before `vagrant up`

```
config.vm.provision "shell", inline: <<-SHELL
echo 'OPENSHIFT_SUBDOMAIN="$(hostname).$(/opt/adb/openshift/get_ip_address).nip.io"
IMAGE="registry.access.redhat.com/openshift3/ose:v3.1.1.6"' > /etc/sysconfig/openshift_provision
SHELL
```

_Or_
- Run `vagrant up --no-provision`

```
$ vagrant ssh
$ cat etc/sysconfig/openshift_provision
# Modify these options if you want to change openshift hostname
OPENSHIFT_SUBDOMAIN="$(hostname).$(/opt/adb/openshift/get_ip_address).nip.io"
IMAGE="registry.access.redhat.com/openshift3/ose:v3.1.1.6"
# sudo systemctl start openshift
```

If user already  started vagrant box and then want to change the config. (**Not recommended because app configuration and local configuration gets deleted**)  

```
# vagrant ssh
# sudo su -
# systemctl stop openshift
# umount /var/lib/openshift/openshift.local.volumes/pods/*/volumes/kubernetes.io~secret/*
# rm -fr /var/lib/openshift/
Edit openshift_option file
$ cat etc/sysconfig/openshift_provision
# Modify these options if you want to change openshift hostname
OPENSHIFT_SUBDOMAIN="$(hostname).$(/opt/adb/openshift/get_ip_address).nip.io"
IMAGE="registry.access.redhat.com/openshift3/ose:v3.1.1.6"
# systemctl start openshift
```

**Comment by LalatenduMohanty** [comment] 2016-04-15 06:35
@praveenkumar thanks , I used below to the CDK OSE  Vagrantfile and it worked fine for me

```
config.vm.provision "shell", inline: <<-SHELL
    sudo sed -i 's/xip.io/nip.io/' /etc/sysconfig/openshift_option
  SHELL
```

**Comment by LalatenduMohanty** [comment] 2016-04-15 06:40
@hferentschik @praveenkumar  what would be your suggestion  with respect to just one solution which we should document?

**Comment by LalatenduMohanty** [comment] 2016-04-15 06:43
Also @bexelbie @navidshaikh , what will be your suggestion?

**Comment by navidshaikh** [comment] 2016-04-15 07:41
We have a script to add insecure registry https://github.com/projectatomic/adb-utils/blob/master/utils/add_insecure_registry, its convenient, user does not need to know the underlying details, IMO the solution we should go ahead should be minimal and easy for user to do. 
Although having a script to change the hostname could be too much efforts, can we look for an option where we can embed this action in `sccli` / or some unified CLI for adb-utils?
And if its something we can not afford to add in the `sccli` ATM, IMO we should aim for minimal lines in Vagrantfile. As @LalatenduMohanty and @praveenkumar  mentioned

```
config.vm.provision "shell", inline: <<-SHELL
    sudo sed -i 's/xip.io/nip.io/' /etc/sysconfig/openshift_option
  SHELL
```

This is only 3 lines addition and (Vagrant) users should be familiar with workaround updating Vagrantfiles.

P.S Long term, since this could be a frequent request from users, I suggest we should look at providing an option for it in unified CLI for adb-utils.

**Comment by hferentschik** [comment] 2016-04-15 08:53
Interesting. First of all I would like to know why one wants to use nip.io over xip.io. If nip.io is really the more reliable solution, sure. That would somehow imply that xip.io does sometimes not respond. To document this as a solution for corporate network issues is wrong. xip.io and nip.io do exactly the same thing, so I don't think switching from one to another will solve any networking issues one has due to company network/VPN settings. 

Regarding how to enable this, editing _/etc/sysysconfig/openshift_option_ works. On the first bootstrap that is. This won't help when the user wants to switch from xip.io to nip.io some time after startup, even if the user explicitly uses _--provision_. The problem is in the [openshift](https://github.com/projectatomic/adb-utils/blob/master/services/openshift/scripts/openshift#L76) startup script. It only generates the OpenShift config files if there are no config files at all. So in this case one needs to edit the OpenShift master config. I guess this is a general "issue" we need to discuss, whether changes to _/etc/sysysconfig/openshift_option_ should apply on restarts of the OpenShift service. If so, we would need to change the _openshift_ script.

**Comment by optak** [comment] 2016-04-15 09:13
Yesterday, I tried to do s/xip.io/nip.io/ for /etc/sysysconfig/openshift_option.  If openshift has started already, I did the same for openshift master config and than `vagrant service-manager restart openshift`. It worked, but only for new routes, existing ones still used xip.io.
In case of changing just the 1st script during 1st boot of VM, it worked well for me.

I don't have enough time for testing stability of nip.io currently, but fox xip.io, I didn't see any problems until this week. It would be much better to:
a) use landrush (+works offline)
b) create another server for such dns service on internet
c) create such service on host (better in box, but there would be problem with dns of box)

**Comment by hferentschik** [comment] 2016-04-15 09:42
> I did the same for openshift master config and than vagrant service-manager restart openshift

hmm, it did? I need to test this as well then. Surprises me a bit

> It worked, but only for new routes, existing ones still used xip.io.

Sure, existing routes will not be affected. They are already created and one needs to use _oc_ to change them.

> I don't have enough time for testing stability of nip.io currently, but fox xip.io, I didn't see any problems until this week.

I also have not noticed any problems yet. Just ran 1000 random xip.io queries and all returned in a total of 1m9s:

```
time for i in {1..1000} ; do dig $((RANDOM%=255))"."$((RANDOM%=255))"."$((RANDOM%=255))"."$((RANDOM%=255)).xip.io; done
```

> a) use landrush (+works offline)

That's probably the best route and still one of our goals. The pull request which makes Landrush work on Windows is finally merged. There is still a bit of work, but hopefully we can push a Landrush release out soon.

> b) create another server for such dns service on internet

This has been discussed as well. Makes sense I guess. We would be in control of the service and could handle potential issues. Also we could create a "nice" url. However, it also means we need the infrastructure to setup this service and we need to maintain it. 

> c) create such service on host (better in box, but there would be problem with dns of box)

That effectively Landrush, no? Writing such a service is actually not the hard bit, but if you want to run it locally on your host, the tricky bit is to configure your local DNS to contact this DNS service. Also, you want to be careful here. The simplest route is to install a DNS service and let it act a s proxy. It handles certain types of request directly (xip.io style) whereas others will be proxied through the actual DNS server of the host. This is probably easiest to configure, but if this proxy goes rouge the host looses pretty much all connectivity to the outside world. Hence the approach which also Landrush takes, configure the hosts DNS setup to only route specific URLs to the custom DNS server.

**Comment by optak** [comment] 2016-04-15 10:30
I agree with @hferentschik on and I would also prefer landrush from all that options.
Fox xip.io issue ... when we noticed something is wrong, we dig into it with @dkutalek, with tools: host, dig, ping, ... and there was intervals of several tens of minutes without issue, sometimes short problem, sometimes xip.io wasn't working for several minutes.
Small taste of results:

```
14:38:02        OK
14:38:03        ping: unknown host xip.io
14:38:05        ping: unknown host xip.io
(...)
14:38:41        ping: unknown host xip.io
14:38:42        ping: unknown host xip.io
14:38:43        OK
14:38:44        OK
14:38:46        OK

```

We experienced problem with xip.io from all tested places: Brno and Boston corporate network and from university network in Brno (different dns server), so it looks pretty sure that problem has xip.io itself and not some network node between.

**Comment by LalatenduMohanty** [comment] 2016-04-15 10:41
> To document this as a solution for corporate network issues is wrong. xip.io and nip.io do exactly the same thing, so I don't think switching from one to another will solve any networking issues one has due to company network/VPN settings.

@hferentschik I have updated the issue with more generic text.

**Comment by praveenkumar** [comment] 2016-05-30 04:37
@LalatenduMohanty do we still waiting to docs to resolve it? Also we already have a issue from @hferentschik about enabling landrush which will obsolete this bug.

**Comment by bexelbie** [comment] 2016-06-06 09:35
I believe we should not document changing DNS services until we receive a user request for such.  By the time that user comes into existance we may already be using landrush.  I vote to close.

Additionally, in talking to @tnozicka this morning, it may be a DNSSEC issue so none of these services is going to work.

**Comment by tnozicka** [comment] 2016-06-06 10:25
btw. At home I am using DNSSEC resolvers:
- 217.31.204.130
- 193.29.206.206

from https://www.nic.cz/odvr/

and both xip.io and nip.io don't work.

**Comment by praveenkumar** [comment] 2016-07-22 06:30
@LalatenduMohanty @hferentschik I am closing this issue now because this is going to taken care by landrush.

**Closed as completed by praveenkumar** 2016-07-22 06:30 UTC
Labels: documenation
