### ISSUE TITLE
freshly started cdk wont let you reach your service, restarting cdk solves it

### ISSUE THREAD

**Issue by adietish** [projectatomic/adb-utils#139] opened 2016-06-08 15:36 UTC
My setup:
- OS: FC23
- vagrant: 1.8.1
- CDK: rhel-cdk-kubernetes-7.2-25.x86_64.vagrant-virtualbox.box (build date: 08062016)
- Virtualbox: 4.3-4.3.38_106717

How to reproduce:
1) ASSERT: make sure that you have an application running, with everything in place (service, route, pod)
2) EXEC: reboot your machine, launch cdk
3) EXEC: Try to reach your service via browser/wget

Result:
App is not reachable, browser returns a html telling you that the service is not reachable even though everything seems in place: the service with its route, the pods, everything in place correctly.
![image](https://cloud.githubusercontent.com/assets/25126/15906661/23f0acce-2dba-11e6-96f0-adaa5fba2dd0.png)
With wget you get a 503 back

```
--2016-06-08 22:06:57--  http://eap-app-p1.rhel-cdk.10.1.2.2.xip.io/index.jsf
Resolving eap-app-p1.rhel-cdk.10.1.2.2.xip.io (eap-app-p1.rhel-cdk.10.1.2.2.xip.io)... 10.1.2.2
Connecting to eap-app-p1.rhel-cdk.10.1.2.2.xip.io (eap-app-p1.rhel-cdk.10.1.2.2.xip.io)|10.1.2.2|:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2016-06-08 22:06:57 ERROR 503: Service Unavailable.
```

4) EXEC: Restart cdk (vagrant reload or vagrant halt && vagrant up)

Result:
App is reachable in browser/wget

```
--2016-06-08 22:12:57--  http://eap-app-p1.rhel-cdk.10.1.2.2.xip.io/index.jsf
Resolving eap-app-p1.rhel-cdk.10.1.2.2.xip.io (eap-app-p1.rhel-cdk.10.1.2.2.xip.io)... 10.1.2.2
Connecting to eap-app-p1.rhel-cdk.10.1.2.2.xip.io (eap-app-p1.rhel-cdk.10.1.2.2.xip.io)|10.1.2.2|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4018 (3.9K) [text/html]
Saving to: ‘index.jsf.4’

index.jsf.4                                                            100%[==========================================================================================================================================================================>]   3.92K  --.-KB/s    in 0s      

```

**Comment by praveenkumar** [comment] 2016-06-09 10:37
I didn't able to reproduce it

```
[HOST]# vagrant up 
Bringing machine 'default' up with 'libvirt' provider...
==> default: Uploading base box image as volume into libvirt storage...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:              work_default
==> default:  -- Domain type:       kvm
==> default:  -- Cpus:              2
==> default:  -- Memory:            3072M
==> default:  -- Management MAC:    
==> default:  -- Loader:            
==> default:  -- Base box:          cdk_test
==> default:  -- Storage pool:      default
==> default:  -- Image:             /var/lib/libvirt/images/work_default.img (41G)
==> default:  -- Volume Cache:      default
==> default:  -- Kernel:            
==> default:  -- Initrd:            
==> default:  -- Graphics Type:     vnc
==> default:  -- Graphics Port:     5900
==> default:  -- Graphics IP:       127.0.0.1
==> default:  -- Graphics Password: Not defined
==> default:  -- Video Type:        cirrus
==> default:  -- Video VRAM:        9216
==> default:  -- Keymap:            en-us
==> default:  -- INPUT:             type=mouse, bus=ps2
==> default:  -- Command line : 
==> default: Creating shared folders metadata...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Configuring and enabling network interfaces...
==> default: Registering box with vagrant-registration...
    default: Would you like to register the system now (default: yes)? [y|n]y
    default: username: prkumar@redhat.com
    default: password: 
==> default: Rsyncing folder: /root/work/ => /vagrant
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Created symlink from /etc/systemd/system/multi-user.target.wants/openshift.service to /usr/lib/systemd/system/openshift.service.
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: 
==> default: Successfully started and provisioned VM with 2 cores and 3072 MB of memory.
==> default: To modify the number of cores and/or available memory set the environment variables
==> default: VM_CPU respectively VM_MEMORY.
==> default: You can now access the OpenShift console on: https://10.1.2.2:8443/console
==> default: To use OpenShift CLI, run:
==> default: $ vagrant ssh
==> default: $ oc login 10.1.2.2:8443
==> default: 
==> default: Configured users are (<username>/<password>):
==> default: openshift-dev/devel
==> default: admin/admin
==> default: If you have the oc client library on your host, you can also login from your host.

[HOST# curl -Ik https://10.1.2.2:8443
HTTP/1.1 200 OK
Content-Type: application/json
Date: Thu, 09 Jun 2016 15:53:38 GMT
Content-Length: 203

[HOST]# systemctl reboot
Connection to 10.70.49.106 closed by remote host.
Connection to 10.70.49.106 closed.

[prkumar@localhost ~]$ ssh root@10.70.49.106
root@10.70.49.106's password: 
Last login: Thu Jun  9 21:06:24 2016 from dhcp193-117.pnq.redhat.com

[HOST]# vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Waiting for SSH to become available...
==> default: Creating shared folders metadata...
==> default: Rsyncing folder: /root/work/ => /vagrant
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: 
==> default: Successfully started and provisioned VM with 2 cores and 3072 MB of memory.
==> default: To modify the number of cores and/or available memory set the environment variables
==> default: VM_CPU respectively VM_MEMORY.
==> default: 
==> default: You can now access the OpenShift console on: https://10.1.2.2:8443/console
==> default: 
==> default: To use OpenShift CLI, run:
==> default: $ vagrant ssh
==> default: $ oc login 10.1.2.2:8443
==> default: 
==> default: Configured users are (<username>/<password>):
==> default: openshift-dev/devel
==> default: admin/admin
==> default: 
==> default: If you have the oc client library on your host, you can also login from your host.
[HOST]# curl -Ik https://10.1.2.2:8443
HTTP/1.1 200 OK
Content-Type: application/json
Date: Thu, 09 Jun 2016 15:58:43 GMT
Content-Length: 203

[HOST]# vagrant ssh
Last login: Thu Jun  9 11:51:04 2016

[GUEST-CDK]$ docker ps
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED              STATUS              PORTS               NAMES
4e28a01c6e10        prom/haproxy-exporter:latest                          "/bin/haproxy_exporte"   23 seconds ago       Up 21 seconds                           k8s_metrics-exporter.6a69a2ca_router-1-rrgwy_default_15d9ef37-2e5a-11e6-a00c-525400e1cc4c_cf8782b4
5ea38e6988b8        openshift3/ose-docker-registry:v3.2.0.44              "/bin/sh -c 'DOCKER_R"   36 seconds ago       Up 32 seconds                           k8s_registry.a918bee1_docker-registry-2-g17ax_default_1590497f-2e5a-11e6-a00c-525400e1cc4c_a4b91f28
e95773245a70        openshift3/ose-haproxy-router:v3.2.0.44               "/usr/bin/openshift-r"   38 seconds ago       Up 34 seconds                           k8s_router.ee59efe7_router-1-rrgwy_default_15d9ef37-2e5a-11e6-a00c-525400e1cc4c_fb76c676
2b543d2cb0d1        openshift3/ose-pod:v3.2.0.44                          "/pod"                   42 seconds ago       Up 37 seconds                           k8s_POD.d9aefd41_docker-registry-2-g17ax_default_1590497f-2e5a-11e6-a00c-525400e1cc4c_23f8d4c0
3659c63b6f78        openshift3/ose-pod:v3.2.0.44                          "/pod"                   42 seconds ago       Up 38 seconds                           k8s_POD.6305dc28_router-1-rrgwy_default_15d9ef37-2e5a-11e6-a00c-525400e1cc4c_4e9972be
9f9b16698292        registry.access.redhat.com/openshift3/ose:v3.2.0.44   "/usr/bin/openshift s"   About a minute ago   Up About a minute                       openshift

[GUEST-CDK]$ exit
logout
Connection to 192.168.121.107 closed.
```

**Comment by jeffmaury** [comment] 2016-06-09 11:00
We are using vagrant

**Comment by praveenkumar** [comment] 2016-06-09 11:05
@jeffmaury In above comment I am also using vagrant, didn't get what you want to say?

**Comment by jeffmaury** [comment] 2016-06-09 11:30
My fault I meant VirtualBox

**Comment by LalatenduMohanty** [comment] 2016-06-09 13:37
@optak have you seen this?

**Comment by optak** [comment] 2016-06-09 13:47
@LalatenduMohanty: not yet, someone can test it soon.
But it's reported with vagrant-1.8.1, which is not fully compatible with ADB/CDK, it may be the root cause.
I also don't know which Vagrantfile was used,
but for rhel-ose and vagrant-1.7.4, I get working ose without reboot (passed > 5 times, no fail)
If this is only reproducible with vagrant-1.8.1, I would close it.

**Comment by adietish** [comment] 2016-06-09 13:53
@optak I am using the cdk.zip that's alongside the builds in http://cdk-builds.usersys.redhat.com/builds/weekly/latest-build/. Timestamp on it is 08062016

**Comment by alexeykazakov** [comment] 2016-06-09 14:08
@adietish @jeffmaury the question is what vagrant version you are using. CDK recommends 1.7.4 (and this is what our windows dev suite installer installs) because of some issues in 1.8.x

**Comment by adietish** [comment] 2016-06-09 14:12
@alexeykazakov as reported in the issue description, i have vagrant 1.8.1
I can check if I can use vagrant 1.7.4 on my FC23, more interesting would be what version @jeffmaury is using

**Comment by alexeykazakov** [comment] 2016-06-09 14:13
@adietish could you please test it on 1.7.4?

**Comment by optak** [comment] 2016-06-09 14:34
@adietish for downgrading, you should do this before:
- destroy all VM
- remove box
- remove .vagrant (in dir where Vagrantfile is)

**Comment by praveenkumar** [comment] 2016-06-09 15:30
So I am able to reproduced this issue and trying to find the root cause because what I can see that we are not able to get service endpoints.

```
# oc get services
NAME             CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
nodejs-example   172.30.179.107   <none>        8080/TCP   11m

#  curl -Ik 172.30.179.107:8080
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: text/html; charset=utf-8
Content-Length: 40382
ETag: W/"9dbe-1JmfkBUY/av+bFVWtUNjJg"
Date: Thu, 09 Jun 2016 15:23:33 GMT
Connection: keep-alive

# oc get endpoints --selector=nodejs-example 
That doesn't showing anything which is why we are not able to see it but route is created which complaining about 'not serving requests at this endpoint'

#  oc get route
NAME             HOST/PORT                                                PATH      SERVICE          TERMINATION   LABELS
nodejs-example   nodejs-example-sample-project.rhel-cdk.10.1.2.2.xip.io             nodejs-example                 app=nodejs-example,template=nodejs-example
```

**Comment by amit82github** [comment] 2016-06-09 15:36
@optak i have tested with vagrant version 1.7.4 , cdk build http://cdk-builds.usersys.redhat.com/builds/weekly/08-Jun-2016.rc1/ and no issue found on fedora 23. I deployed nojdes example and perl and able to access the .xip.io file without any fail.

**Comment by LalatenduMohanty** [comment] 2016-06-10 04:16
I tried the latest CDK build on Vagrant 1.7.4 with Virtualbox.  I can access service fine. Now will update to Vagrant 1.8.1 and see if it works.

**Comment by LalatenduMohanty** [comment] 2016-06-10 04:37
nodejs-example works for me with Vagrant 1.8.1 . I am using Virtualbox 5.0.16. 

```
[vagrant@rhel-cdk ~]$ oc status
In project OpenShift sample project (sample-project) on server https://127.0.0.1:8443

http://nodejs-example-sample-project.rhel-cdk.10.1.2.2.xip.io (svc/nodejs-example)
  dc/nodejs-example deploys istag/nodejs-example:latest <-
    bc/nodejs-example builds https://github.com/openshift/nodejs-ex.git with openshift/nodejs:0.10 
    deployment #1 deployed about a minute ago - 1 pod

```

```
[vagrant@rhel-cdk ~]$ oc get endpoints --selector=nodejs-example 
[vagrant@rhel-cdk ~]$ oc get route
NAME             HOST/PORT                                                PATH      SERVICE          TERMINATION   LABELS
nodejs-example   nodejs-example-sample-project.rhel-cdk.10.1.2.2.xip.io             nodejs-example                 template=nodejs-example
[vagrant@rhel-cdk ~]$ oc get endpoints --selector=nodejs-example 
```

Not sure why `oc get endpoints` not giving any output.

From my workstation i.e. Mac I could see the application in the browser and also through `curl nodejs-example-sample-project.rhel-cdk.10.1.2.2.xip.io`

**Comment by amitkrout** [comment] 2016-06-10 05:52
@LalatenduMohanty i have also tested it on fedora 23 with latest cdk rc1 build, vagrant version 1.7.4 . Found same observation with different oc template (nodejs, perl, python) what you mentioned above. I deployed all oc template outside openshift sample project.

**Comment by praveenkumar** [comment] 2016-06-10 06:11
@LalatenduMohanty @amitkrout you folks have to check problem statement again. What I think you folks only followed first 2 steps.
1. Deploy CDK using ose vagrantfile
2. Create a application (nodejs-example)
3. Restart your Host
4. Start deployed cdk again (using `vagrant up`)

Try to access that app now from web.

**Comment by LalatenduMohanty** [comment] 2016-06-10 06:16
@praveenkumar right. But from the discussion with @adietish I remember he was also seeing the issue in first two steps. May be that changed in with the latest build. 

When we say reboot your machine, is it the workstation or the vagrant guest?

**Comment by amitkrout** [comment] 2016-06-10 07:31
@praveenkumar i restarted the host and first time started cdk using the `vagrant up`. I am able to access all the deployed app (nodejs, perl, python) from web.

**Comment by adietish** [comment] 2016-06-10 08:14
@LalatenduMohanty for me this happened if I restarted my laptop and once it was up, launched the cdk. I'm downgrading vagrant and trying again.

**Comment by hferentschik** [comment] 2016-06-10 08:49
> for me this happened if I restarted my laptop and once it was up, launched the cdk. I'm downgrading vagrant and trying again.

@adietish  Do you _halt_ the VM before you restart the laptop? If not this is not going to work. We have discussed this somewhere already (need to find the link). If you just shut down your laptop, VirtualBox does not know what to do with your running VM. It puts it into a state which is not properly managed by Vagrant and hence when you after a reboot start the CDK, the required provisioning scripts are not run. When you then do a _vagrant reload_ or similar the appropriate hooks are run.

Just to confirm that, can you also open the VirtualBox management UI. Check the VM is running and then reboot the machine. Once back up open the UI again and check the state the VM is in.

**Comment by hferentschik** [comment] 2016-06-10 08:52
So here is some relevant info provided you are actually experiencing this issue - https://github.com/mitchellh/vagrant/issues/495

Note, I have the same issue on OS X. The aborted state of VirtualBox is not managed by Vagrant. You have thee choices:
- Just live with it and reload the VM after a host reboot
- Make sure to suspend/halt the VM explicitly before you reboot
- Write some script which on reboot will make sure all VMs get properly suspended

**Comment by adietish** [comment] 2016-06-10 13:57
@hferentschik yes, indeed, this seems related. It wont happen if I suspend the vm before rebooting. If I have the cdk running and reboot (without suspending the cdk), virtualbox shows the vm in "powered off" state. Same in vagrant. Seems correct to me?
Vagrant 1.7.4 or 1.8.1 makes no difference. I can reproduce the issue in both vagrant versions.

**Comment by praveenkumar** [comment] 2016-06-13 05:39
This is not related to vagrant specific version. As @hferentschik pointed out that this upstream issue and from vagrant side it's already closed (because this is something Virtualbox should do). If you all folks agree then I will close this issue here also, better you folks use script which are present to https://github.com/mitchellh/vagrant/issues/495

**Comment by adietish** [comment] 2016-06-13 19:41
ok, works for me.

**Closed as completed** 2016-06-14 03:36 UTC
Labels: bug

**Comment by mglantz** [comment] 2016-09-12 20:51
I saw this issue after reboot of MacOS and CDK via VirtualBox latest (Version 5.0.26 r108824).
Problem solved with 'vagrant reload', normal reboot of CDK VM did not work.
