### ISSUE TITLE
Wrong hostname for exposed registry route

### ISSUE THREAD

**Issue by hferentschik** [projectatomic/adb-utils#31] opened 2016-02-15 19:23 UTC
In _/opt/adb/openshift/openshift_provision_ we have:

```
  registry_host_name="hub.$(hostname)"
  oc expose service docker-registry --hostname ${registry_host_name}
```

`hostname` does not seem to be set anywhere. The resulting route becomes (accidentally!?) _hub.localhost.localdomain_, but it should be something like _hub.cdk.10.1.2.2.xip.io_.

It seems nothing is passed to the provision script either (_/usr/lib/systemd/system/openshift.service_):

```
ExecStartPost=/usr/bin/sh /opt/adb/openshift/openshift_provision
```

**Comment by LalatenduMohanty** [comment] 2016-02-18 10:07
@hferentschik  I think it is workings in a nested manner 

The information goes to the openshift script i.e. `adb-utils/services/openshift` through the openshift.service file

```

# Machine xip.io hostname
host="adb.$ip.xip.io"
```

openshift script dumps the information in `/var/lib/origin/openshift.local.config/master/` and the `openshift_provision` scripts picks it from there.

I am planning to mark this issue as not a bug

**Comment by hferentschik** [comment] 2016-02-18 11:12
the result on my VM after provisioning was still wrong so. When looking at the route I had something like `huv.localhost.localdomain` (or something along these lines). It should be hub.cdk.10.1.1.2.xip.io. So if the problem is not there, it must be somewhere else.

So this is actually a blocker, since we cannot expose the internal registry atm anymore.

**Comment by hferentschik** [comment] 2016-02-24 09:29
Checking the latest build, I am having now _hub.rhel-cdk_. I guess expected, since afaict _openshift_provision_ has not changed yet.

**Comment by hferentschik** [comment] 2016-02-24 09:30
BTW, could we add the label focus:devex

**Comment by LalatenduMohanty** [comment] 2016-02-25 13:06
@hferentschik I tried ADB with OpenShift and I am seeing application is available at http://nodejs-example-testproject.adb.10.1.2.2.xip.io/ . Which looks fine to me. Am I missing something? I will be testing CDK expecting to see something similar i.e. s/adb/cdk/

**Comment by hferentschik** [comment] 2016-02-25 14:08
You need to check the route under which we expose the OpenShift registry:

   sudo oc --config=/var/lib/origin/openshift.local.config/master/admin.kubeconfig get route/docker-registry

should be _hub.cdk.10.1.2.2.xip.io_ or whatever the used host is.

**Comment by LalatenduMohanty** [comment] 2016-03-02 10:38
Closing the issue as the PR is merged now

**Closed as completed by LalatenduMohanty** 2016-03-02 10:38 UTC
Labels: bug, focus:devex, blocker

**Comment by hferentschik** [comment] 2016-03-04 13:19
New route as per CDK Beta5 - hub.openshift.10.1.2.2.xip.io. Works for me.
